language: node_js
node_js:
    - "lts/*"

cache:
    yarn: true
    directories:
        - node_modules

install: yarn

jobs:
    include:
        - stage: Test
          name: Aspect
          script: yarn test:as-ci
