name: Tests

on: [pull_request, push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.14.1"
      - run: yarn install
      - run: yarn build
      - name: Lint
        run: yarn lint
      - name: Check Types
        run: yarn run check-types
      - name: Unit tests
        run: yarn test
