name: Perf

on: [pull_request, push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Bootstrap
        run: yarn
      - name: Run performance tests
        run: node_modules/.bin/ts-node test/perf/all.ts
